// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: © 2026 ribosome-schema contributors

// Regenerates bindings/typescript/src/types.ts from the normative JSON Schemas
// under schema/<CURRENT_SCHEMA_DIR>/. The schemas are the source of truth; the
// TypeScript types — AND the SCHEMA_VERSION constant — are derived artifacts.
// Run after editing any *.schema.json:
//
//   bun run spec:types
//
// We generate types for OUR schemas (manifest, lockfile) only. The manifest
// $refs the external MCP server.json schema — we do NOT inline/generate that
// (it is large, external, and we read only a few fields); instead we map that
// $ref to the hand-maintained `McpServerJson` type
// (bindings/typescript/src/mcp-server-types.ts).
//
// Centralized versioning: manifest and lockfile are versioned together as one
// schema family (they're two views of the same spec release — the lockfile is
// literally defined as "the resolved output of a manifest"). Their
// `schemaVersion` consts MUST be equal; this script refuses to generate if
// they diverge, rather than silently picking one. See README.md "Versioning"
// for the full bump procedure.
//
// Bumping to a new version: create schema/v{N}/ (old versions are never
// deleted or edited — their $id URLs must keep resolving forever), point
// CURRENT_SCHEMA_DIR below at it, then run this script.

const { writeFileSync, readFileSync } = require("node:fs");
const { join } = require("node:path");
const { compile } = require("json-schema-to-typescript");

const root = join(__dirname, "..");
const CURRENT_SCHEMA_DIR = "v1"; // the only place this literal is hand-typed
const schemaDir = join(root, "schema", CURRENT_SCHEMA_DIR);
const tsDir = join(root, "bindings", "typescript", "src");

// Redirect the external server.json $id to a stub that emits the hand-typed
// `McpServerJson` reference instead of the full generated shape.
const serverRefResolver = {
  order: 1,
  canRead: (file) => file.url.includes("static.modelcontextprotocol.io"),
  read: () => JSON.stringify({ tsType: "McpServerJson" }),
};

const options = {
  bannerComment: "",
  additionalProperties: false,
  $refOptions: { resolve: { mcpServer: serverRefResolver } },
};

function loadSchema(schemaFile) {
  return JSON.parse(readFileSync(join(schemaDir, schemaFile), "utf8"));
}

async function gen(schema, rootName) {
  return compile(schema, rootName, options);
}

(async () => {
  const manifestSchema = loadSchema("manifest.schema.json");
  const lockfileSchema = loadSchema("lockfile.schema.json");

  const manifestVersion = manifestSchema.properties?.schemaVersion?.const;
  const lockfileVersion = lockfileSchema.properties?.schemaVersion?.const;
  if (!manifestVersion || manifestVersion !== lockfileVersion) {
    throw new Error(
      `manifest.schema.json schemaVersion (${JSON.stringify(manifestVersion)}) and ` +
        `lockfile.schema.json schemaVersion (${JSON.stringify(lockfileVersion)}) must be ` +
        `identical — they're versioned together as one schema family. Fix the *.schema.json ` +
        `files, don't patch this generated output.`,
    );
  }
  for (const [name, schema] of [
    ["manifest", manifestSchema],
    ["lockfile", lockfileSchema],
  ]) {
    const expected = `/${CURRENT_SCHEMA_DIR}/`;
    if (!schema.$id?.includes(expected)) {
      throw new Error(
        `${name}.schema.json $id (${schema.$id}) does not contain "${expected}" — ` +
          `$id and CURRENT_SCHEMA_DIR (in this script) must agree.`,
      );
    }
  }

  // REUSE-IgnoreStart
  // (these two lines are a string literal written into the generated file's
  // own header, not this script's header — reuse-tool otherwise misreads
  // them as an invalid SPDX expression on gen-types.js itself)
  const header = [
    "// SPDX-License-Identifier: Apache-2.0",
    "// SPDX-FileCopyrightText: © 2026 ribosome-schema contributors",
    // REUSE-IgnoreEnd
    "",
    "// GENERATED by `bun run spec:types` from the normative JSON Schemas.",
    `// Do not edit by hand — edit schema/${CURRENT_SCHEMA_DIR}/*.schema.json and regenerate.`,
    "",
    "// McpServerJson is hand-typed (see mcp-server-types.ts); the manifest $ref maps to it.",
    'import type { McpServerJson } from "./mcp-server-types";',
    "",
    "/**",
    " * Version of the ribosome manifest/lockfile schema family. The single source of",
    ` * truth is schema/${CURRENT_SCHEMA_DIR}/*.schema.json's \`schemaVersion\` const — this is`,
    " * extracted from there, not hand-typed. Manifest and lockfile always share one",
    ' * version; see README.md "Versioning".',
    " */",
    `export const SCHEMA_VERSION = ${JSON.stringify(manifestVersion)} as const;`,
    "",
  ].join("\n");

  const parts = await Promise.all([
    gen(manifestSchema, "RibosomeManifest"),
    gen(lockfileSchema, "RibosomeLockfile"),
  ]);
  writeFileSync(join(tsDir, "types.ts"), header + parts.join("\n"));
  console.log(`generated bindings/typescript/src/types.ts (SCHEMA_VERSION=${manifestVersion})`);
})().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
