// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: © 2026 ribosome-schema contributors

// Regenerates bindings/typescript/src/types.ts from the normative JSON Schemas
// under schema/v1/. The schemas are the source of truth; the TypeScript types
// are a derived artifact. Run after editing any *.schema.json:
//
//   npm run spec:types
//
// We generate types for OUR schemas (manifest, lockfile) only. The manifest
// $refs the external MCP server.json schema — we do NOT inline/generate that
// (it is large, external, and we read only a few fields); instead we map that
// $ref to the hand-maintained `McpServerJson` type
// (bindings/typescript/src/mcp-server-types.ts).

const { writeFileSync, readFileSync } = require("node:fs");
const { join } = require("node:path");
const { compile } = require("json-schema-to-typescript");

const root = join(__dirname, "..");
const schemaDir = join(root, "schema", "v1");
const tsDir = join(root, "bindings", "typescript", "src");

// Redirect the external server.json $id to a stub that emits the hand-typed
// `McpServerJson` reference instead of the full generated shape.
const serverRefResolver = {
  order: 1,
  canRead: (file) => file.url.includes("static.modelcontextprotocol.io"),
  read: () => JSON.stringify({ tsType: "McpServerJson" }),
};

const header = [
  "// SPDX-License-Identifier: Apache-2.0",
  "// SPDX-FileCopyrightText: © 2026 ribosome-schema contributors",
  "",
  "// GENERATED by `npm run spec:types` from the normative JSON Schemas.",
  "// Do not edit by hand — edit schema/v1/*.schema.json and regenerate.",
  "",
  '// McpServerJson is hand-typed (see mcp-server-types.ts); the manifest $ref maps to it.',
  'import type { McpServerJson } from "./mcp-server-types";',
  "",
].join("\n");

const options = {
  bannerComment: "",
  additionalProperties: false,
  $refOptions: { resolve: { mcpServer: serverRefResolver } },
};

async function gen(schemaFile, rootName) {
  const schema = JSON.parse(readFileSync(join(schemaDir, schemaFile), "utf8"));
  return compile(schema, rootName, options);
}

(async () => {
  const parts = await Promise.all([
    gen("manifest.schema.json", "RibosomeManifest"),
    gen("lockfile.schema.json", "RibosomeLockfile"),
  ]);
  writeFileSync(join(tsDir, "types.ts"), header + parts.join("\n"));
  console.log("generated bindings/typescript/src/types.ts");
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
