// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: © 2026 ribosome-schema contributors

// GENERATED by `bun run spec:types` from the normative JSON Schemas.
// Do not edit by hand — edit schema/v1/*.schema.json and regenerate.

// McpServerJson is hand-typed (see mcp-server-types.ts); the manifest $ref maps to it.
import type { McpServerJson } from "./mcp-server-types";

/**
 * Version of the ribosome manifest/lockfile schema family. The single source of
 * truth is schema/v1/*.schema.json's `schemaVersion` const — this is
 * extracted from there, not hand-typed. Manifest and lockfile always share one
 * version; see README.md "Versioning".
 */
export const SCHEMA_VERSION = "1" as const;
/**
 * An MCP server, declared as one of three sources.
 */
export type McpServer = RegistryServer | InlineServer | ProcessServer;
/**
 * Opaque permission scopes requested by this server, passed through to the orchestrator. Semantics are defined by the consuming orchestrator, not by ribosome.
 */
export type Permissions = string[];
/**
 * Compatibility bridge: a raw local process launch, field-compatible with .mcp.json / editor MCP config for copy-paste migration. Not runtime-resolved by ribosome — the command is the caller's responsibility (though it runs inside the project runtime pool's environment).
 */
export type ProcessServer = {
  [k: string]: unknown;
} & {
  source: "process";
  /**
   * Executable to launch, e.g. "npx".
   */
  command: string;
  args?: string[];
  env?: {
    [k: string]: string;
  };
  transport?: "stdio" | "http";
  /**
   * Required when transport is "http".
   */
  url?: string;
  permissions?: Permissions;
};

/**
 * Declares a project's tool/runtime versions and MCP servers so ribosome can resolve and materialize them up front. This is the normative source of truth for the manifest format; TypeScript types are generated from it.
 */
export interface RibosomeManifest {
  /**
   * Optional pointer to this schema, for editor tooling.
   */
  $schema?: string;
  /**
   * Manifest format version. Bumped only on breaking changes.
   */
  schemaVersion: "1";
  /**
   * Tool/runtime version requirements for the project's own packages and tools. These also act as the version policy for the runtime families that MCP servers need (e.g. declaring node here pins the node used by npm-based MCP servers).
   */
  runtimes?: {
    /**
     * Requested version spec, e.g. "24", "3.12", "20.11.0".
     */
    [k: string]: string;
  };
  /**
   * Named MCP registry sources this project resolves against.
   */
  registries?: {
    /**
     * Name of the source used by registry servers that omit an explicit `registry`.
     */
    default?: string;
    /**
     * Map of source name -> registry source.
     */
    sources: {
      [k: string]: RegistrySource;
    };
  };
  /**
   * Map of local server id -> server declaration.
   */
  mcpServers?: {
    [k: string]: McpServer;
  };
  /**
   * RESERVED (v1): paths to external MCP config files (.mcp.json, .vscode/mcp.json, ...) to import. The import parser lands in a later minor version; declaring this field now keeps that capability additive and non-breaking.
   */
  extends?: string[];
}
export interface RegistrySource {
  /**
   * Registry protocol. Selects the registry adapter. Defaults to the official MCP Registry API.
   */
  type?: string;
  /**
   * Base URL of the registry.
   */
  url: string;
  /**
   * HTTP headers to send when resolving against this source, e.g. for an authenticated subregistry. Each header's value is read from the named environment variable at resolve time -- never store a literal credential here.
   */
  auth?: RegistryAuthHeader[];
}
export interface RegistryAuthHeader {
  /**
   * HTTP header name, e.g. "Authorization" or "X-Api-Key".
   */
  header: string;
  /**
   * Name of the environment variable to read the header's literal value from at resolve time.
   */
  envVar: string;
}
/**
 * A server resolved from a named registry by reverse-DNS name (+ optional version). The registry response (server.json) determines runtime, transport and launch — not this manifest.
 */
export interface RegistryServer {
  source: "registry";
  /**
   * Name of a `registries.sources` entry. Defaults to `registries.default`.
   */
  registry?: string;
  /**
   * Reverse-DNS server name, e.g. "io.modelcontextprotocol/filesystem".
   */
  name: string;
  /**
   * Exact version to resolve. Omit for the registry's latest.
   */
  version?: string;
  permissions?: Permissions;
}
/**
 * A custom server described inline using the standard MCP server.json shape, so it declares its own packages/runtime/env and participates in resolution exactly like a registry server. Enables a natural custom -> publish-to-registry migration.
 */
export interface InlineServer {
  source: "inline";
  /**
   * A complete server.json document (vendored & pinned; see spec/vendor/).
   */
  server: McpServerJson;
  permissions?: Permissions;
}

/**
 * Everything needed to start or connect to the server.
 */
export type Launch =
  | {
      transport: "stdio";
      /**
       * @minItems 1
       */
      command: [string, ...string[]];
    }
  | {
      transport: "http";
      url: string;
    };

/**
 * The resolved, materialized output of a manifest: a deduplicated runtime pool plus one isolated environment view per consumer (the project and each MCP server). Declarative and portable by design — it carries no shell-specific activation hooks, so any implementation in any language can consume it.
 */
export interface RibosomeLockfile {
  /**
   * Lockfile format version.
   */
  schemaVersion: "1";
  /**
   * ISO 8601 timestamp of resolution.
   */
  resolvedAt: string;
  /**
   * The pinned server.json schema version this lockfile was resolved against, e.g. "2025-12-11".
   */
  mcpSchemaVersion?: string;
  /**
   * Deduplicated set of runtimes materialized for the whole project. One entry per (tool, exact version); shared by every consumer that needs it.
   */
  runtimePool: PooledRuntime[];
  project: Environment;
  mcpServers: ResolvedMcpServer[];
}
export interface PooledRuntime {
  /**
   * Stable pool key, e.g. "node@24.3.0".
   */
  id: string;
  /**
   * Tool name, e.g. "node".
   */
  tool: string;
  /**
   * Version spec as requested, e.g. "24".
   */
  requested: string;
  /**
   * Exact resolved version, e.g. "24.3.0".
   */
  version: string;
}
/**
 * A declarative environment delta pointing at specific pool entries. No shell/activation snippets — those are re-derived by the environment provider when applied.
 */
export interface Environment {
  /**
   * Directories to prepend to PATH, in order.
   */
  pathPrepend: string[];
  /**
   * Environment variables to set.
   */
  envVars: {
    [k: string]: string;
  };
}
export interface ResolvedMcpServer {
  /**
   * Local server id, matching the manifest key.
   */
  id: string;
  /**
   * Pool ids this server's environment selects.
   */
  uses?: string[];
  launch: Launch;
  environment: Environment;
  permissions?: string[];
}
