# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2026 ribosome-schema contributors

name: ci

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run test
